[package]
name = "celepkg"
version = "0.5.1"
description = "A Celeste map manager"
authors = ["celepkg"]
repository = "https://github.com/panic-0/celepkg"
publish = false
edition = "2021"

[lib]
name = "celepkg_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dirs = "6"
quick-xml = "0.37"
rayon = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tauri = { version = "2", features = [] }
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.10.1"
tempfile = "3"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "parsing"] }
walkdir = "2"
xxhash-rust = { version = "0.8", features = ["xxh64"] }
zip = "2"
